# Generated by Django 4.2 on 2023-05-08 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comida_menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('stock', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='comida', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True, max_length=100)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('id_comida', models.ForeignKey(db_column='id_comida', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.comida_menu')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
                ('fecha_inicio', models.DateField(max_length=100)),
                ('fecha_fin', models.DateField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_comida', models.ForeignKey(db_column='id_comida', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.comida_menu')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCumple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
                ('fecha_inicio', models.DateField(max_length=100)),
                ('fecha_fin', models.DateField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCategoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descuento', models.FloatField()),
                ('fecha_inicio', models.DateField(max_length=100)),
                ('fecha_fin', models.DateField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.categoria')),
            ],
        ),
    ]
