# Generated by Django 4.2 on 2023-05-01 04:13

import app_restaurante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0002_usuarios_comida_menu_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name=app_restaurante.models.Pedidos.total),
        ),
    ]
