# Generated by Django 4.2 on 2023-05-15 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0003_alter_usuarios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
