# Generated by Django 4.2 on 2023-05-01 21:06

import app_restaurante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0004_remove_usuarios_usuario_alter_pedidos_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name=app_restaurante.models.Pedidos.total),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
