# Generated by Django 4.2 on 2023-05-01 22:43

import app_restaurante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0005_alter_pedidos_total_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name=app_restaurante.models.Pedidos.calcular_total),
        ),
    ]
