# Generated by Django 4.2 on 2023-05-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0005_usuarios_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='authenticated',
        ),
    ]
