# Generated by Django 4.2 on 2023-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0006_remove_usuarios_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida_menu',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
