# Generated by Django 4.2 on 2023-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0007_alter_comida_menu_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
