# Generated by Django 4.2 on 2023-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0010_alter_pedidos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
