# Generated by Django 4.2 on 2023-05-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0021_informacionventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentocumple',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
