# Generated by Django 4.2 on 2023-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0024_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='estado',
        ),
        migrations.AddField(
            model_name='delivery',
            name='id_factura',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
