# Generated by Django 4.2 on 2023-05-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurante', '0025_remove_delivery_estado_delivery_id_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='total',
            new_name='totalFactura',
        ),
    ]
